### ISSUE TITLE
Create EDA Graphs and put them on the website

### ISSUE THREAD

**Issue by jacob-umich** [jacob-umich/stats-dash#5]
## Background
From my understanding, the first part of the EDA was to clean and merge the data, and the second part is to generate several plots to explain the data. The plots and explanations go in the first part of the dashboard, then the machine learning model follows them. This task focuses on generating the plots on the dashboard to explain the dataset we have.

> For the EDA part, you will need to show at least 15 interactive diagrams showing correlations, frequencies, and/or relationships between various independent and dependent variables with plots of 5 different types (bar, line, heatmap, etc.). Every plot should have a title and the x/y axis should have legible labels without any label overlaps for full credit. Explain your assumptions and your EDA question before the plot and then your actual findings after every plot.

## Tasks
 - [ ] generate a plot showing the distribution of questions
 - [ ] generate 14 other plots plots
 - [ ] explain them on the webpage

**Comment by jacob-umich** [comment]
@Aerlenbeck we need to work on putting your plots on the webpage using the Plotly library I think.

**Comment by Aerlenbeck** [comment]
@jacob-umich I am confused as to how to move forward. I see you compiled all of the EDA but I don't see how they are compiled. On my end, I still see 4 separate files and they are not all the same. I need all of the definitions I made for the SDOH plots. I just added another file of the plots for the SDOH data, but again I'm not sure how to put this into the webpage (are we using main.py for the webpage?)

We still need more diverse plot types. I have >15 plots but they are all bar/chloropleth. Tomorrow I will move onto the nutrition/food price data and hopefully I can do a line plot there, but then we still need two more plot types. Not sure if anyone has a creative solution.

**Comment by jacob-umich** [comment]
@Aerlenbeck I am working on a few examples now on how to put them on the main.py file. The data is aggregated into a health.db file, an sqlite database that has both datasets in it (and any more we add later). We can query the db just for the data we need for each figure and it should ideally take less time than loading the whole dataset for each figure.

**Comment by Aerlenbeck** [comment]
Okay, I guess I'm not entirely sure what you mean. I have only been using pandas for all of my queries, but writing all of those was very time consuming so I don't want to redo all of them in sql. @jacob-umich

**Comment by jacob-umich** [comment]
@Aerlenbeck You don't necessarily have to. You just have to load the part of the data your queries affect using sql, then perform the queries using pandas. I just uploaded my examples.

**Comment by jacob-umich** [comment]
@tsivitse @amandarcicali can you create several plots related to questions you're interested in. you can copy what I did on my last commit to EDA to make your plots. I will probably make a few more plots related to the distribution of questions.

**Comment by Aerlenbeck** [comment]
@jacob-umich I do not understand how I would do this. Why do we need to use sql?

**Comment by jacob-umich** [comment]
@Aerlenbeck we dont need to, but it helps us in a few ways

1. add more modules required by the project
2. makes the website run faster by only loading the data we need
3. uses the saved version of the cleaned data instead of re-running the cleaning operations each time

**Comment by Aerlenbeck** [comment]
Okay, the example didn't load before but I see it now. That is not too complicated. I can make those changes but it won't be until tomorrow. 

Also, is your example plot file what you want me to add my plots onto so it stays condensed?

@jacob-umich

**Comment by Aerlenbeck** [comment]
Also, when I update the EDA file, do you want me to keep it in the SDOH cleaning file or should I put it somewhere else where we can have everything compiled? Because the .db just has the data, if I am understanding correctly.

**Comment by jacob-umich** [comment]
@Aerlenbeck  sorry for not replying to these. 

> Also, is your example plot file what you want me to add my plots onto so it stays condensed?
I think that would be good

> put it somewhere else where we can have everything compiled? Because the .db just has the data, if I am understanding correctly

yea i have this "data_handler" script i've been putting everything in.

I started adding your plots to the main page but I have to stop soon. I though I would upload my work in the meantime. I started to make your plots dynamic, changing what is displayed on them with buttons and stuff. I think this will be good for selecting the question/years

**Comment by Aerlenbeck** [comment]
@jacob-umich 

Okay great, I will try to model the rest of the plots/definitions after what you did. I think I understand it well enough. Do I need to add the dash callbacks under all of the plots or does that have to do with the main.py file?

**Comment by jacob-umich** [comment]
@Aerlenbeck the callbacks just make them so you switch the values live

**Comment by tsivitse** [comment]
I figured out how to get the charts working and should have them done by tomorrow

**Comment by tsivitse** [comment]
For the chart code, should I copy paste it in the eda_plots.py file or the main.py file?

**Comment by jacob-umich** [comment]
@tsivitse put it in the plots file. 

@Aerlenbeck @amandarcicali Can you all upload your current changes so I don't redo anything you have done?

**Comment by Aerlenbeck** [comment]
@jacob-umich They are uploaded, I didn't make any changes yesterday.

**Comment by jacob-umich** [comment]
@Aerlenbeck I got the rest of your plots in. I made them so you can change what year/question you look at. If you could add some commentary to them, that would be good. In total, we have 8/15 plots now, and we need 3 different plot types still. @tsivitse @amandarcicali I will add 2 more plots and you guys can handle the last 5.

**Comment by Aerlenbeck** [comment]
@jacob-umich Are you counting the drop down plots as one plot? That should have 12 bar plots combined into one, plus the 6 other plots for a total of 18, but I understand counting it as one plot if that's what you are doing! If so I am happy to make more plots. I can do food prices/nutrition stuff if we are still missing that.

Yes I think it is good to add commentary. Do you want me to add it on the main.py file?

**Comment by Aerlenbeck** [comment]
>I made a special function for the text block. It formats it and everything. You write the text in a separate file  under the text_scripts folder, then give the file name as an input argument.

Okay, I understand what you are doing here. I can replicate your formatting to add text that way. Are you able to upload any .txt file as .md like the files you already have in text_scripts? Lmk if that doesn't make sense


> That works for me! we have to make a ml model related to this stuff, I think a good option would be one that predicts life expectancy based on diabetes/disability/etc.

Okay great, this might even relate back to the SDOH trends too which would be cool! I think we could also do where you give the state you live in and it predicts disability status/diabetes/life expectancy. Though I do not really get ml so I'm not sure if that's a dumb idea lol

@jacob-umich

**Comment by jacob-umich** [comment]
> Okay, I understand what you are doing here. I can replicate your formatting to add text that way. Are you able to upload any .txt file as .md like the files you already have in text_scripts? Lmk if that doesn't make sense

yea its just a text file but you can change the file extension (.txt) from .txt to .md 


> Okay great, this might even relate back to the SDOH trends too which would be cool! I think we could also do where you give the state you live in and it predicts disability status/diabetes/life expectancy. Though I do not really get ml so I'm not sure if that's a dumb idea lol

we can make a model for that but it might not predict as well just because there is only 4 data points for each state (each year that data was recorded).

**Comment by tsivitse** [comment]
@Aerlenbeck  So we need 5 different plot types? What plot types do we have currently?

**Comment by jacob-umich** [comment]
> @Aerlenbeck So we need 5 different plot types? What plot types do we have currently?

we have bar and cloropleth. I am working on a sunburst plot now

**Comment by Aerlenbeck** [comment]
@jacob-umich 

That makes sense! We can do the ml you're thinking of then since that should work better.

**Comment by tsivitse** [comment]
I will do some scatter plots then of alcohol usage vs. life expectancy

**Comment by jacob-umich** [comment]
I just pushed the sunburst. I also changed up the style some... The next thing I am going to work on is getting our app set up with gcp

**Comment by tsivitse** [comment]
does the datahandler have life expectancy data? I'm trying to get the RATE column from the life expectancy data but am getting an error:
Code:
import data_handler as dh
# only the columns you need
df= dh.get_cdi_field("topic,yearstart,question,datavaluetype,stratificationcategory1,locationdesc,datavalue, RATE")
Error:
DatabaseError: Execution failed on sql 'select topic,yearstart,question,datavaluetype,stratificationcategory1,locationdesc,datavalue, RATE from cdi': no such column: RATE

**Comment by jacob-umich** [comment]
@tsivitse 

datahandler does have life expectancy data, but youll want to use `dh.simple_life(year)` or make a new function. ` dh.get_cdi_field` just gets data from the disease indicators dataset. Also, all the fields are lowercase in these databases, so you'd want to use "rate" instead of "RATE"

**Comment by tsivitse** [comment]
I added 3 scatter plots to the eda_plots.py file in the eda branch. They are not in your dh format, but I can try to update them to that format tomorrow if you think it's necessary

**Comment by tsivitse** [comment]
do I need to do a pull request to merge what's in the eda_plots.py file in the eda branch with that in the main branch so that my charts show up in the webpage?

**Comment by jacob-umich** [comment]
@tsivitse we will need to do a pull request, but I will need to pull in the changes on the GCP, the re-deploy the app

**Comment by Aerlenbeck** [comment]
I added a scatter plot of obesity prevalence US wide.  I followed your dh format I believe @jacob-umich, but I'm not 100% sure I did it correctly. I also tried to add the dash callbacks, but again, I'm unsure if those are correct.

**Comment by jacob-umich** [comment]
@Aerlenbeck ill take a look

@tsivitse did you see my comments on your commit ?

**Comment by Aerlenbeck** [comment]
@jacob-umich 

I tried to add it to the main.py file but I am confused about how to add it since it's not filtering for a year

**Comment by tsivitse** [comment]
@jacob-umich I did, trying to fix them now. I think like you said earlier I need to create a new data handler function to combine the cdi and le tables

**Comment by jacob-umich** [comment]
@Aerlenbeck since you're plotting across the year, you can just remove the year radio buttons. in the main file, that just means removing the radio object from that plot. Ill fix it and push it so you and @tsivitse can see what I mean

**Comment by Aerlenbeck** [comment]
Okay, I'm going to start adding the text for the other plots then. 

@jacob-umich

**Comment by jacob-umich** [comment]
@Aerlenbeck okay I pushed the change but there are a few things I think need to change with the graph for it to make sense. 
1. the data set you're using just has state information and not US-wide info, so reducing the data to just US data makes it so nothing plots
2. you kept the question dropdown box but set the labels so its just referring to obesity. If we change the question to something else, the labels are misleading
3. I had to comment out the `markers` kwarg because it wasn't supported in my version of plotly xpress. 

I think changing the dropdown box to look at different states would be better. If you want me to make this change I can. If you were wanting to show something different, I can help you change it to that too

**Comment by Aerlenbeck** [comment]
@jacob-umich 

Can we make it a drop down line plot where the drop down menu is each state, and then it has the overall obesity prevalence for that state for all 4 years? If this makes sense.

I can try to make these changes but I am incredibly confused as to how to format things at this point. If you think doing something else would be better I'm totally fine with that. I just wanted to get another plot type in. 

@jacob-umich

**Comment by jacob-umich** [comment]
@Aerlenbeck yes i think that is the easiest fix. I will do that

**Comment by tsivitse** [comment]
have either of you made plots that look at life expectancy as a function of some question (i.e. diabetes)?

**Comment by tsivitse** [comment]
I'm thinking I need to add this code to merge the two tables into the data_handler.py, and then create another function to query that table. Does that sound right?
 #dh to combine le and cdi tables
def cdi_le(topic, locationabbr, question, yearstart):
    # Retrieve data from the 'cdi' table
    cdi_query = f"""
        SELECT topic, locationabbr, question, yearstart, datavalue
        FROM cdi
        WHERE topic = '{topic}'
        AND locationabbr = '{locationabbr}'
        AND question = '{question}'
        AND yearstart = {yearstart}
    """
    cdi_data = pd.read_sql_query(cdi_query, conn)
    
    # Retrieve data from the 'le' table
    le_query = f"""
        SELECT year, state, rate
        FROM le
        WHERE year = {yearstart}
        AND state = '{locationabbr}'
    """
    le_data = pd.read_sql_query(le_query, conn)
    
    # Merge the two dataframes on the common columns
    merged_data = pd.merge(cdi_data, le_data, left_on=['yearstart', 'locationabbr'], right_on=['year', 'state'])
    
    return merged_data

**Comment by jacob-umich** [comment]
> have either of you made plots that look at life expectancy as a function of some question (i.e. diabetes)?

@tsivitse  yes, on my most recent commit, made some related to obesity, smoking, and lack of sleep

**Comment by tsivitse** [comment]
so do we have all the charts now?

**Comment by jacob-umich** [comment]
all of mine are in one technically. I think it would be good to include yours still. I made a figure for those because I was going to use them in the machine learning model.

**Comment by tsivitse** [comment]
Ok, what's the df called that combines the cdi & le tables?

**Comment by amandarcicali** [comment]
I just made a histogram that can go with the map and bar charts of % of adults with diabetes. I think it should go after the other 2 diabetes plots but I don't know how to make sure it does. I was trying to add the year options but I don't think I did that correctly.

**Comment by jacob-umich** [comment]
@tsivitse there isnt one dataframe that combines them all. I think merging them is the right move. I followed your example for my `coorelation` function in the eda_plot file. As far as what you said in the above comment, I think that all sounds good.

**Comment by Aerlenbeck** [comment]
@jacob-umich 

Okay I added text explainers for all our SDOH plot and then an overall conclusion and stuff. I also tried to add one for my obesity plot but I can't find it in the main.py file, has it been added there?

**Comment by jacob-umich** [comment]
I only see sdoh conclusions

**Comment by tsivitse** [comment]
I added in the cdi_le combined table, and functions to get the alcohol scatter plot data. Where can we test if it works?

**Comment by Aerlenbeck** [comment]
Intro and disability are above dis_year

Diabetes is above diab_year

They show up on my end

**Comment by jacob-umich** [comment]
> I added in the cdi_le combined table, and functions to get the alcohol scatter plot data. Where can we test if it works?

you can run the website on your computer by running main.py. is that what you mean?

**Comment by tsivitse** [comment]
I just want to know if my code works, to run main.py we need to push the eda branch we've been working in into the main branch right?

**Comment by jacob-umich** [comment]
it should work in the eda branch

**Comment by jacob-umich** [comment]
@amandarcicali @tsivitse  I fixed your plots. please pull my latest commit, format the plots and add explanation around them

**Comment by tsivitse** [comment]
do we do that in the main or eda_plot file?

**Comment by jacob-umich** [comment]
@tsivitse main

**Comment by tsivitse** [comment]
any idea why i'm getting this error when trying to push my changes to the eda branch?

PS C:\Users\CTsiv\OneDrive - Umich\Desktop\stats507\stats-dash> git push origin eda
To github.com:jacob-umich/stats-dash.git
 ! [rejected]        eda -> eda (non-fast-forward)
error: failed to push some refs to 'github.com:jacob-umich/stats-dash.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by jacob-umich** [comment]
yea it says it in the error

>  (e.g. hint: 'git pull ...') before pushing again.

run `git pull` to incorporate the changes i made

**Comment by tsivitse** [comment]
this is what I get when I do git pull:
error: Your local changes to the following files would be overwritten by merge:
        model.pkl
Please commit your changes or stash them before you merge.
Aborting
Merge with strategy ort failed.

If i then do git stash, and then git push origin eda, I get this error: error: failed to push some refs to 'github.com:jacob-umich/stats-dash.git'

**Comment by jacob-umich** [comment]
delete the model.pkl file, commit any changes you've made, then pull and resolve the merge issues if there are any. the pkl file is binary so git can't merge it. The last model.pkl file is the on I trained for the final version so don't overwrite it

**Comment by tsivitse** [comment]
can you hop on a zoom call to help me resolve it, I don't want to overwrite anything

**Comment by jacob-umich** [comment]
For sure

**Comment by jacob-umich** [comment]
@tsivitse https://umich.zoom.us/j/2533176941

**Comment by jacob-umich** [comment]
@amandarcicali were you going to put any text on the webpage?

**Comment by amandarcicali** [comment]
@jacob-umich i wrote about all three diabetes plots in diabetes.md file and i thought it was already on the webpage
